# Generated by Django 5.1.5 on 2025-03-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=False, verbose_name='Is onboarded'),
        ),
    ]
