# Generated by Django 5.1.5 on 2025-03-29 11:37

import razexOne.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=razexOne.storages.PublicMediaStorage, upload_to='profile_pictures/', verbose_name='Profile picture'),
        ),
    ]
