# Generated by Django 5.1.5 on 2025-03-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
