# Generated by Django 5.1.5 on 2025-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_app_notification',
            field=models.BooleanField(default=True, verbose_name='Allow app notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Is email verified'),
        ),
    ]
