# Generated by Django 5.1.5 on 2025-04-03 17:00

import base.helpers.phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_allow_app_notification_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number must be in E.164 format (e.g., +911234567890).', max_length=15, unique=True, validators=[base.helpers.phone_number.validate_phone_number], verbose_name='Phone number')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_sent_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number must be in E.164 format (e.g., +911234567890).', max_length=255, null=True, validators=[base.helpers.phone_number.validate_phone_number], verbose_name='Phone number'),
        ),
    ]
