# Generated by Django 5.1.5 on 2025-02-11 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_eventcategory_eventcity_event_category_event_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
    ]
