# Generated by Django 5.1.5 on 2025-02-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_event_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueLayout',
            fields=[
                ('layout_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='layout',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.venuelayout'),
        ),
        migrations.CreateModel(
            name='VenueLayoutSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.venuelayout')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.venuelayoutsection'),
        ),
        migrations.DeleteModel(
            name='EventSection',
        ),
    ]
