# Generated by Django 5.1.5 on 2025-02-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_category_event_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartline',
            unique_together={('cart', 'product')},
        ),
    ]
