# Generated by Django 5.1.5 on 2025-02-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_cartline_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
