# Generated by Django 5.1.5 on 2025-03-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_orderline_order_remove_orderline_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_promo_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='applied_quota_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_promoter',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('all_products', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_fixed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('max_order_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(null=True)),
                ('quantity_step', models.IntegerField(default=1)),
                ('priority', models.IntegerField(default=0)),
                ('applicable_user_type', models.CharField(choices=[('PROMOTER', 'Promoter'), ('END_USER', 'End User'), ('ALL', 'All')], default='ALL', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.event')),
                ('products', models.ManyToManyField(to='booking.product')),
                ('promo_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='quota',
            name='promo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='booking.promotion'),
        ),
    ]
