# Generated by Django 5.1.5 on 2025-03-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_promotion_promo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, to='booking.product'),
        ),
    ]
