# Generated by Django 5.1.5 on 2025-03-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_promotion_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_fixed',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
