# Generated by Django 5.1.5 on 2025-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_promotion_discount_fixed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_promoter',
        ),
        migrations.AddField(
            model_name='cart',
            name='end_user_discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_promoter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='end_user_discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='end_user_discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='quotas', to='booking.product'),
        ),
    ]
