# Generated by Django 5.1.5 on 2025-03-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_order_is_promoter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='parent_event',
        ),
        migrations.AddField(
            model_name='event',
            name='cities',
            field=models.ManyToManyField(related_name='events', to='booking.eventcity'),
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(related_name='events', to='booking.artist'),
        ),
        migrations.CreateModel(
            name='Subevent',
            fields=[
                ('subevent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('city', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.eventcity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.event')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.subevent'),
        ),
    ]
