# Generated by Django 5.1.5 on 2025-03-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_artist_remove_event_city_remove_event_parent_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='events', to='booking.artist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='booking.eventcategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='events', to='booking.eventcity'),
        ),
    ]
