# Generated by Django 5.1.5 on 2025-03-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_event_created_at_event_highlights_event_price_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.eventcategory')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='events', to='booking.subcategory'),
        ),
    ]
