# Generated by Django 5.1.5 on 2025-03-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tac',
            field=models.TextField(blank=True, null=True),
        ),
    ]
