# Generated by Django 5.1.5 on 2025-03-29 11:37

import django.db.models.deletion
import razexOne.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_event_tac'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=razexOne.storages.PublicMediaStorage, upload_to='artists/'),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=razexOne.storages.PublicMediaStorage, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=razexOne.storages.PublicMediaStorage, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='subevent',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, storage=razexOne.storages.PublicMediaStorage, upload_to='subevents/'),
        ),
        migrations.AddField(
            model_name='venuelayout',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=razexOne.storages.PublicMediaStorage, upload_to='venue_layouts/'),
        ),
        migrations.AddField(
            model_name='venuelayoutsection',
            name='coordinates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, storage=razexOne.storages.PublicMediaStorage, upload_to='event_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.event')),
            ],
        ),
    ]
