# Generated by Django 5.1.5 on 2025-03-29 19:02

import razexOne.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_artist_image_event_hero_image_eventcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(storage=razexOne.storages.PublicMediaStorage, upload_to='event_images/'),
        ),
    ]
