# Generated by Django 5.1.5 on 2025-03-29 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_eventimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuelayout',
            name='image_height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='venuelayout',
            name='image_width',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
