# Generated by Django 5.1.5 on 2025-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_date_max',
            field=models.DateField(blank=True, null=True, verbose_name='Maximum value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_date_min',
            field=models.DateField(blank=True, null=True, verbose_name='Minimum value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_datetime_max',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Maximum value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_datetime_min',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Minimum value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_number_max',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True, verbose_name='Maximum value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_number_min',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True, verbose_name='Minimum value'),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_string_length_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum length'),
        ),
    ]
