# Generated by Django 5.1.5 on 2025-03-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_alter_answer_answer_alter_question_valid_date_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('N', 'Number'), ('S', 'Text (one line)'), ('T', 'Multiline text'), ('B', 'Yes/No'), ('F', 'File upload'), ('D', 'Date'), ('H', 'Time'), ('W', 'Date and time'), ('TEL', 'Phone number')], help_text='\n        The expected type of answer. Valid options:\n        N - number\n        S - one-line string\n        T - multi-line string\n        B - boolean\n        F - file upload\n        D - date\n        H - time\n        W - date and time\n        TEL - telephone number\n        ', max_length=5, verbose_name='Question type'),
        ),
    ]
