# Generated by Django 5.1.5 on 2025-04-03 17:00

import razexOne.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, storage=razexOne.storages.PrivateMediaStorage, upload_to='answers/'),
        ),
    ]
