# Generated by Django 5.1.5 on 2025-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_alter_event_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['position', 'start_date']},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AddField(
            model_name='event',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promotion',
            name='is_listed',
            field=models.BooleanField(default=True, help_text='Can normal users see this promotion?'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
